#+title: Config
#+startup: showeverything

* CORE & DEFAULTS
** PROJECTILE
#+BEGIN_SRC emacs-lisp
(setq projectile-project-search-path '(("~/projects" . 2) ("~/.config" . 1)))
#+end_src

#+begin_src emacs-lisp

;; (when (memq window-system '(mac ns x))
;;   (setq exec-path-from-shell-variables '("PATH" "GOPATH" "GOROOT" "GO111MODULE"))
;;   (exec-path-from-shell-initialize))

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!

;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.com")
#+end_src

** FONTS
#+begin_src emacs-lisp
;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;
(setq doom-font (font-spec :family "Fira Code" :size 14 :weight 'semi-light)
      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 14))
#+end_src

** DOOM
#+begin_src emacs-lisp
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-one)
(map! :leader
      :desc "Load new theme" "h t" #'counsel-load-theme)
#+end_src

** LINE NUMBERS
#+begin_src emacs-lisp
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)
(global-visual-line-mode t)
#+end_src

** LINE SETTINGS
I set comment-line to 'SPC TAB TAB' which is a rather comfortable keybinding for me on my ZSA Moonlander keyboard.  The standard Emacs keybinding for comment-line is 'C-x C-;'.  The other keybindings are for commands that toggle on/off various line-related settings.  Doom Emacs uses 'SPC t' for "toggle" commands, so I choose 'SPC t' plus 'key' for those bindings.

| COMMAND                  | DESCRIPTION                               | KEYBINDING  |
|--------------------------+-------------------------------------------+-------------|
| comment-line             | /Comment or uncomment lines/                | SPC TAB TAB |
| hl-line-mode             | /Toggle line highlighting in current frame/ | SPC t h     |
| global-hl-line-mode      | /Toggle line highlighting globally/         | SPC t H     |
| doom/toggle-line-numbers | /Toggle line numbers/                       | SPC t l     |
| toggle-truncate-lines    | /Toggle truncate lines/                     | SPC t t     |

#+BEGIN_SRC emacs-lisp
(map! :leader
      :desc "Comment or uncomment lines"      "TAB TAB" #'comment-line
      (:prefix ("t" . "toggle")
       :desc "Toggle line numbers"            "l" #'doom/toggle-line-numbers
       :desc "Toggle line highlight in frame" "h" #'hl-line-mode
       :desc "Toggle line highlight globally" "H" #'global-hl-line-mode
       :desc "Toggle truncate lines"          "t" #'toggle-truncate-lines))
#+END_SRC


** TRASH
#+begin_src emacs-lisp
(setq delete-by-moving-to-trash t)


#+end_src

** GIT
#+begin_src emacs-lisp
(setenv "GIT_LFS_SKIP_SMUDGE" "1")
;; Force VC to refresh branch info on auto-revert
(setq auto-revert-check-vc-info t)
#+end_src

** SUBWORD MODE
#+begin_src emacs-lisp
(global-subword-mode 1)
#+end_src


** MOUSE SUPPORT
Adding mouse support in the terminal version of Emacs.

#+begin_src emacs-lisp
(xterm-mouse-mode 1)
#+end_src


** SPLITS
I set splits to default to opening on the right using 'prefer-horizontal-split'.  I set a keybinding for 'clone-indirect-buffer-other-window' for when I want to have the same document in two splits.  The text of the indirect buffer is always identical to the text of its base buffer; changes made by editing either one are visible immediately in the other.  But in all other respects, the indirect buffer and its base buffer are completely separate.  For example, I can fold one split but other will be unfolded.

#+BEGIN_SRC emacs-lisp
(defun prefer-horizontal-split ()
  (set-variable 'split-height-threshold nil t)
  (set-variable 'split-width-threshold 40 t)) ; make this as low as needed
(add-hook 'markdown-mode-hook 'prefer-horizontal-split)
(map! :leader
      :desc "Clone indirect buffer other window" "b c" #'clone-indirect-buffer-other-window)
#+END_SRC


** WINNER MODE
Winner mode has been included with GNU Emacs since version 20.  This is a global minor mode and, when activated, it allows you to “undo” (and “redo”) changes in the window configuration with the key commands 'SCP w <left>' and 'SPC w <right>'.

#+BEGIN_SRC emacs-lisp
(map! :leader
      (:prefix ("w" . "window")
       :desc "Winner redo" "<right>" #'winner-redo
       :desc "Winner undo" "<left>"  #'winner-undo))
#+END_SRC


** REGISTERS
Emacs registers are compartments where you can save text, rectangles and positions for later use. Once you save text or a rectangle in a register, you can copy it into the buffer once or many times; once you save a position in a register, you can jump back to that position once or many times.  The default GNU Emacs keybindings for these commands (with the exception of counsel-register) involves 'C-x r' followed by one or more other keys.  I wanted to make this a little more user friendly, and since I am using Doom Emacs, I choose to replace the 'C-x r' part of the key chords with 'SPC r'.

| COMMAND                          | DESCRIPTION                      | KEYBINDING |
|----------------------------------+----------------------------------+------------|
| copy-to-register                 | /Copy to register/                 | SPC r c    |
| frameset-to-register             | /Frameset to register/             | SPC r f    |
| insert-register                  | /Insert contents of register/      | SPC r i    |
| jump-to-register                 | /Jump to register/                 | SPC r j    |
| list-registers                   | /List registers/                   | SPC r l    |
| number-to-register               | /Number to register/               | SPC r n    |
| counsel-register                 | /Interactively choose a register/  | SPC r r    |
| view-register                    | /View a register/                  | SPC r v    |
| window-configuration-to-register | /Window configuration to register/ | SPC r w    |
| increment-register               | /Increment register/               | SPC r +    |
| point-to-register                | /Point to register/                | SPC r SPC  |

#+BEGIN_SRC emacs-lisp
(map! :leader
      (:prefix ("r" . "registers")
       :desc "Copy to register" "c" #'copy-to-register
       :desc "Frameset to register" "f" #'frameset-to-register
       :desc "Insert contents of register" "i" #'insert-register
       :desc "Jump to register" "j" #'jump-to-register
       :desc "List registers" "l" #'list-registers
       :desc "Number to register" "n" #'number-to-register
       :desc "Interactively choose a register" "r" #'counsel-register
       :desc "View a register" "v" #'view-register
       :desc "Window configuration to register" "w" #'window-configuration-to-register
       :desc "Increment register" "+" #'increment-register
       :desc "Point to register" "SPC" #'point-to-register))
#+END_SRC


** ZAP TO CHAR
Emacs provides a 'zap-to-char' command that kills from the current point to a character.  It is bound to 'M-z' in standard GNU Emacs but since Doom Emacs uses 'SPC' as its leader key and does not have 'SPC z' binded to anything, it just makes since to use it for 'zap-to-char'.  Note that 'zap-to-char' can be used with the universal argument 'SPC u' to modify its behavior.  Examples of 'zap-to-char' usage are listed in the table below:

| KEYBINDING                | WHAT IS DOES                                               |
|---------------------------+------------------------------------------------------------|
| SPC z e                   | /deletes all chars to the next occurrence of 'e'/            |
| SPC u 2 SPC z e           | /deletes all chars to the second occurrence of 'e'/          |
| SPC u - SPC z e           | /deletes all chars to the previous occurrence of 'e'/        |
| SPC u - 2 SPC z e         | /deletes all chars to the second previous occurrence of 'e'/ |
| SPC u 1 0 0 SPC u SPC z e | /deletes all chars to the 100th occurrence of 'e'/           |

=TIP=: The universal argument (SPC u) can only take a single integer by default.  If you need to use a multi-digit number (like 100 in the last example in the table above), then you must terminate the universal argument with another 'SPC u' after typing the number.

'zap-up-to-char' is an alternative command that does not zap the char specified.  It is binded to 'SPC Z'.  It can also be used in conjunction with the universal argument 'SPC u' in similar fashion to the the 'zap-to-char' examples above.

=NOTE=:  Vim (evil mode) has similar functionality builtin.  You can delete to the next occurrence of 'e' by using 'dte' in normal.  To delete to the next occurrence of 'e' including the 'e', then you would use 'dfe'.  And you can modify 'dt' and 'df' by prefixing them with numbers, so '2dte' would delete to the second occurrence of 'e'.

#+BEGIN_SRC emacs-lisp
(map! :leader
      :desc "Zap to char"    "z" #'zap-to-char
      :desc "Zap up to char" "Z" #'zap-up-to-char)
#+END_SRC


** INSERT DATE
Some custom functions to insert the date.  The function 'insert-todays-date' can be used one of three different ways: (1) just the keybinding without the universal argument prefix, (2) with one universal argument prefix, or (3) with two universal argument prefixes.  The universal argument prefix is 'SPC-u' in Doom Emacs (C-u in standard GNU Emacs).  The function 'insert-any-date' only outputs to one format, which is the same format as 'insert-todays-date' without a prefix.

| COMMAND               | EXAMPLE OUTPUT            | KEYBINDING            |
|-----------------------+---------------------------+-----------------------|
| dt/insert-todays-date | /Friday, November 19, 2021/ | SPC i d t             |
| dt/insert-todays-date | /11-19-2021/                | SPC u SPC i d t       |
| dt/insert-todays-date | /2021-11-19/                | SPC u SPC u SPC i d t |
| dt/insert-any-date    | /Friday, November 19, 2021/ | SPC i d a             |

#+begin_src emacs-lisp
(defun dt/insert-todays-date (prefix)
  (interactive "P")
  (let ((format (cond
                 ((not prefix) "%A, %B %d, %Y")
                 ((equal prefix '(4)) "%m-%d-%Y")
                 ((equal prefix '(16)) "%Y-%m-%d"))))
    (insert (format-time-string format))))

(require 'calendar)
(defun dt/insert-any-date (date)
  "Insert DATE using the current locale."
  (interactive (list (calendar-read-date)))
  (insert (calendar-date-string date)))

(map! :leader
      (:prefix ("i d" . "Insert date")
        :desc "Insert any date"    "a" #'dt/insert-any-date
        :desc "Insert todays date" "t" #'dt/insert-todays-date))
#+end_src


** BOOKMARKS AND BUFFERS
Doom Emacs uses 'SPC b' for keybindings related to bookmarks and buffers.

*** Bookmarks
Bookmarks are somewhat like registers in that they record positions you can jump to.  Unlike registers, they have long names, and they persist automatically from one Emacs session to the next. The prototypical use of bookmarks is to record where you were reading in various files.

| COMMAND         | DESCRIPTION                            | KEYBINDING |
|-----------------+----------------------------------------+------------|
| list-bookmarks  | /List bookmarks/                         | SPC b L    |
| bookmark-set    | /Set bookmark/                           | SPC b m    |
| bookmark-delete | /Delete bookmark/                        | SPC b M    |
| bookmark-save   | /Save current bookmark to bookmark file/ | SPC b w    |

#+BEGIN_SRC emacs-lisp
(setq bookmark-default-file "~/.config/doom/bookmarks")

(map! :leader
      (:prefix ("b". "buffer")
       :desc "List bookmarks"                          "L" #'list-bookmarks
       :desc "Set bookmark"                            "m" #'bookmark-set
       :desc "Delete bookmark"                         "M" #'bookmark-delete
       :desc "Save current bookmarks to bookmark file" "w" #'bookmark-save))
#+END_SRC

*** Buffers
Regarding /buffers/, the text you are editing in Emacs resides in an object called a /buffer/. Each time you visit a file, a buffer is used to hold the file’s text. Each time you invoke Dired, a buffer is used to hold the directory listing.  /Ibuffer/ is a program that lists all of your Emacs /buffers/, allowing you to navigate between them and filter them.

| COMMAND         | DESCRIPTION          | KEYBINDING |
|-----------------+----------------------+------------|
| ibuffer         | /Launch ibuffer/       | SPC b i    |
| kill-buffer     | /Kill current buffer/  | SPC b k    |
| next-buffer     | /Goto next buffer/     | SPC b n    |
| previous-buffer | /Goto previous buffer/ | SPC b p    |
| save-buffer     | /Save current buffer/  | SPC b s    |

*** Global Auto Revert
A buffer can get out of sync with respect to its visited file on disk if that file is changed by another program. To keep it up to date, you can enable Auto Revert mode by typing M-x auto-revert-mode, or you can set it to be turned on globally with 'global-auto-revert-mode'.  I have also turned on Global Auto Revert on non-file buffers, which is especially useful for 'dired' buffers.

#+begin_src emacs-lisp
(global-auto-revert-mode 1)
(setq global-auto-revert-non-file-buffers t)
#+end_src

*** Keybindings within ibuffer mode
| COMMAND                           | DESCRIPTION                            | KEYBINDING |
|-----------------------------------+----------------------------------------+------------|
| ibuffer-mark-forward              | /Mark the buffer/                        | m          |
| ibuffer-unmark-forward            | /Unmark the buffer/                      | u          |
| ibuffer-do-kill-on-deletion-marks | /Kill the marked buffers/                | x          |
| ibuffer-filter-by-content         | /Ibuffer filter by content/              | f c        |
| ibuffer-filter-by-directory       | /Ibuffer filter by directory/            | f d        |
| ibuffer-filter-by-filename        | /Ibuffer filter by filename (full path)/ | f f        |
| ibuffer-filter-by-mode            | /Ibuffer filter by mode/                 | f m        |
| ibuffer-filter-by-name            | /Ibuffer filter by name/                 | f n        |
| ibuffer-filter-disable            | /Disable ibuffer filter/                 | f x        |
| ibuffer-do-kill-lines             | /Hide marked buffers/                    | g h        |
| ibuffer-update                    | /Restore hidden buffers/                 | g H        |

#+begin_src emacs-lisp
(evil-define-key 'normal ibuffer-mode-map
  (kbd "f c") 'ibuffer-filter-by-content
  (kbd "f d") 'ibuffer-filter-by-directory
  (kbd "f f") 'ibuffer-filter-by-filename
  (kbd "f m") 'ibuffer-filter-by-mode
  (kbd "f n") 'ibuffer-filter-by-name
  (kbd "f x") 'ibuffer-filter-disable
  (kbd "g h") 'ibuffer-do-kill-lines
  (kbd "g H") 'ibuffer-update)
#+end_src


** OPEN SPECIFIC FILES
Keybindings to open files that I work with all the time using the find-file command, which is the interactive file search that opens with 'C-x C-f' in GNU Emacs or 'SPC f f' in Doom Emacs.  These keybindings use find-file non-interactively since we specify exactly what file to open.  The format I use for these bindings is 'SPC =' plus 'key' since Doom Emacs does not use 'SPC ='.

=NOTE=: Doom Emacs already has a function 'doom/open-private-config' set to the keybinding 'SPC f p'.  This allows you to open any file in your HOME/.config/doom directory, so the following keybindings that I created are not really necessary, but I created this section as an example of how to to create bindings that open specific files on your system.

| PATH TO FILE                  | DESCRIPTION                 | KEYBINDING |
|-------------------------------+-----------------------------+------------|
| ~/.config/doom/start.org      | /Edit start.org (start page)/ | SPC = =    |
| ~/Documents/org/agenda.org           | /Edit agenda file/            | SPC = a    |
| ~/.config/doom/config.org     | /Edit doom config.org/        | SPC = c    |
| ~/.config/doom/init.el        | /Edit doom init.el/           | SPC = i    |
| ~/.config/doom/packages.el    | /Edit doom packages.el/       | SPC = p    |
| ~/.config/doom/eshell/aliases | /Edit eshell aliases/         | SPC = e a  |
| ~/.config/doom/eshell/profile | /Edit eshell profile/         | SPC = e p  |

#+BEGIN_SRC emacs-lisp
(map! :leader
      (:prefix ("=" . "open file")
       :desc "Edit start.org"        "=" #'(lambda () (interactive) (find-file "~/.config/doom/start.org"))
       :desc "Edit agenda file"      "a" #'(lambda () (interactive) (find-file "~/Documents/org/agenda.org"))
       :desc "Edit doom config.org"  "c" #'(lambda () (interactive) (find-file "~/.config/doom/config.org"))
       :desc "Edit doom init.el"     "i" #'(lambda () (interactive) (find-file "~/.config/doom/init.el"))
       :desc "Edit doom packages.el" "p" #'(lambda () (interactive) (find-file "~/.config/doom/packages.el"))))
(map! :leader
      (:prefix ("= e" . "open eshell files")
       :desc "Edit eshell aliases"   "a" #'(lambda () (interactive) (find-file "~/.config/doom/eshell/aliases"))
       :desc "Edit eshell profile"   "p" #'(lambda () (interactive) (find-file "~/.config/doom/eshell/profile"))))
#+END_SRC


** EVALUATE ELISP EXPRESSIONS
Changing some keybindings from their defaults to better fit with Doom Emacs, and to avoid conflicts with my window managers which sometimes use the control key in their keybindings.  By default, Doom Emacs does not use 'SPC e' for anything, so I choose to use the format 'SPC e' plus 'key' for these (I also use 'SPC e' for 'eww' keybindings).

| COMMAND         | DESCRIPTION                                  | KEYBINDING |
|-----------------+----------------------------------------------+------------|
| eval-buffer     | /Evaluate elisp in buffer/                     | SPC e b    |
| eval-defun      | /Evaluate the defun containing or after point/ | SPC e d    |
| eval-expression | /Evaluate an elisp expression/                 | SPC e e    |
| eval-last-sexp  | /Evaluate elisp expression before point/       | SPC e l    |
| eval-region     | /Evaluate elisp in region/                     | SPC e r    |

#+Begin_src emacs-lisp
(map! :leader
      (:prefix ("e". "evaluate/ERC/EWW")
       :desc "Evaluate elisp in buffer"  "b" #'eval-buffer
       :desc "Evaluate defun"            "d" #'eval-defun
       :desc "Evaluate elisp expression" "e" #'eval-expression
       :desc "Evaluate last sexpression" "l" #'eval-last-sexp
       :desc "Evaluate elisp in region"  "r" #'eval-region))
#+END_SRC


* UI & APPEARANCE
** MODELINE
The modeline is the bottom status bar that appears in Emacs windows.  For more information on what is available to configure in the Doom modeline, check out:
https://github.com/seagle0128/doom-modeline

#+begin_src emacs-lisp
;; (set-face-attribute 'mode-line nil :font "")
(setq doom-modeline-height 30     ;; sets modeline height
      doom-modeline-bar-width 5   ;; sets right bar width
      doom-modeline-persp-name t  ;; adds perspective name to modeline
      doom-modeline-persp-icon t) ;; adds folder icon next to persp name
#+end_src


** CENTAUR-TABS
To use tabs in Doom Emacs, be sure to uncomment "tabs" in Doom's init.el.  Displays tabs at the top of the window similar to tabbed web browsers such as Firefox.  I don't actually use tabs in Emacs.  I placed this in my config to help others who may want tabs.  In the default configuration of Doom Emacs, 'SPC t' is used for "toggle" keybindings, so I choose 'SPC t c' to toggle centaur-tabs.  The "g" prefix for keybindings is used for a bunch of evil keybindings in Doom, but "g" plus the arrow keys were not used, so I thought I would bind those for tab navigation.  But I did leave the default "g t" and "g T" intact if you prefer to use those for centaur-tabs-forward/backward.

| COMMAND                     | DESCRIPTION               | KEYBINDING       |
|-----------------------------+---------------------------+------------------|
| centaur-tabs-mode           | /Toggle tabs globally/      | SPC t c          |
| centaur-tabs-local-mode     | /Toggle tabs local display/ | SPC t C          |
| centaur-tabs-forward        | /Next tab/                  | g <right> or g t |
| centaur-tabs-backward       | /Previous tab/              | g <left> or g T  |
| centaur-tabs-forward-group  | /Next tab group/            | g <down>         |
| centaur-tabs-backward-group | /Previous tab group/        | g <up>           |

#+BEGIN_SRC emacs-lisp
(setq centaur-tabs-set-bar 'over
      centaur-tabs-set-icons t
      centaur-tabs-gray-out-icons 'buffer
      centaur-tabs-height 24
      centaur-tabs-set-modified-marker t
      centaur-tabs-style "bar"
      centaur-tabs-modified-marker "•")
(map! :leader
      :desc "Toggle tabs globally" "t c" #'centaur-tabs-mode
      :desc "Toggle tabs local display" "t C" #'centaur-tabs-local-mode)
(evil-define-key 'normal centaur-tabs-mode-map (kbd "g <right>") 'centaur-tabs-forward        ; default Doom binding is 'g t'
                                               (kbd "g <left>")  'centaur-tabs-backward       ; default Doom binding is 'g T'
                                               (kbd "g <down>")  'centaur-tabs-forward-group
                                               (kbd "g <up>")    'centaur-tabs-backward-group)
#+END_SRC


** MINIMAP
A minimap sidebar displaying a smaller version of the current buffer on either the left or right side. It highlights the currently shown region and updates its position automatically.  Be aware that this minimap program does not work in Org documents.  This is not unusual though because I have tried several minimap programs and none of them can handle Org.

| COMMAND      | DESCRIPTION                               | KEYBINDING |
|--------------+-------------------------------------------+------------|
| minimap-mode | /Toggle minimap-mode/                       | SPC t m    |

#+begin_src emacs-lisp
(setq minimap-window-location 'right)
(map! :leader
      (:prefix ("t" . "toggle")
       :desc "Toggle minimap-mode" "m" #'minimap-mode))
#+end_src


** TREEMACS
Treemacs is a project-tree drawer (enabled in ~init.el~).  ~treemacs-follow-mode~ keeps the tree pointed at the current file, and unlocking ~treemacs-width-is-initially-locked~ makes the drawer width adjustable.  Since Doom Emacs uses 'SPC t' for 'toggle' keybindings, I used 'SPC t n' to toggle the tree.  (Doom also binds ~+treemacs/toggle~ to 'SPC o p' out of the box.)

| COMMAND                                        | DESCRIPTION                     | KEYBINDING |
|------------------------------------------------+---------------------------------+------------|
| +treemacs/toggle                               | /Toggle treemacs/                 | SPC t n    |
| treemacs-add-and-display-current-project-exclusively | /Show current project in treemacs/ | SPC d n    |

#+BEGIN_SRC emacs-lisp
(after! treemacs
  (setq treemacs-width-is-initially-locked nil)
  (treemacs-follow-mode 1))
(map! :leader
      :desc "Toggle treemacs file viewer" "t n" #'+treemacs/toggle
      :desc "Show project in treemacs"    "d n" #'treemacs-add-and-display-current-project-exclusively)
#+END_SRC


** BEACON
Never lose your cursor.  When you scroll, your cursor will shine!  This is a global minor-mode. Turn it on everywhere with:

#+begin_src emacs-lisp
(beacon-mode 1)
#+end_src


** RAINBOW MODE
Rainbox mode displays the actual color for any hex value color.  It's such a nice feature that I wanted it turned on all the time, regardless of what mode I am in.  The following creates a global minor mode for rainbow-mode and enables it (exception: org-agenda-mode since rainbow-mode destroys all highlighting in org-agenda).

#+begin_src emacs-lisp
(define-globalized-minor-mode global-rainbow-mode rainbow-mode
  (lambda ()
    (when (not (memq major-mode
                (list 'org-agenda-mode)))
     (rainbow-mode 1))))
(global-rainbow-mode 1 )
#+end_src


** CLIPPY
Gives us a popup box with "Clippy, the paper clip". You can make him say various things by calling 'clippy-say' function.  But the more useful functions of clippy are the two describe functions provided: 'clippy-describe-function' and 'clippy-describe-variable'.  Hit the appropriate keybinding while the point is over a function/variable to call it.  A popup with helpful clippy will appear, telling you about the function/variable (using describe-function and describe-variable respectively).

| COMMAND                  | DESCRIPTION                           | KEYBINDING |
|--------------------------+---------------------------------------+------------|
| clippy-describe-function | /Clippy describes function under point/ | SPC c h f  |
| clippy-describe-variable | /Clippy describes variable under point/ | SPC c h v  |

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("c h" . "Help info from Clippy")
       :desc "Clippy describes function under point" "f" #'clippy-describe-function
       :desc "Clippy describes variable under point" "v" #'clippy-describe-variable))

#+end_src


** IVY
Ivy is a generic completion mechanism for Emacs.

*** IVY-POSFRAME
Ivy-posframe is an ivy extension, which lets ivy use posframe to show its candidate menu.  Some of the settings below involve:
+ ivy-posframe-display-functions-alist -- sets the display position for specific programs
+ ivy-posframe-height-alist -- sets the height of the list displayed for specific programs

Available functions (positions) for 'ivy-posframe-display-functions-alist'
+ ivy-posframe-display-at-frame-center
+ ivy-posframe-display-at-window-center
+ ivy-posframe-display-at-frame-bottom-left
+ ivy-posframe-display-at-window-bottom-left
+ ivy-posframe-display-at-frame-bottom-window-center
+ ivy-posframe-display-at-point
+ ivy-posframe-display-at-frame-top-center

=NOTE:= If the setting for 'ivy-posframe-display' is set to 'nil' (false), anything that is set to 'ivy-display-function-fallback' will just default to their normal position in Doom Emacs (usually a bottom split).  However, if this is set to 't' (true), then the fallback position will be centered in the window.

#+BEGIN_SRC emacs-lisp
(setq ivy-posframe-display-functions-alist
      '((swiper                     . ivy-posframe-display-at-point)
        (complete-symbol            . ivy-posframe-display-at-point)
        (counsel-M-x                . ivy-display-function-fallback)
        (counsel-esh-history        . ivy-posframe-display-at-window-center)
        (counsel-describe-function  . ivy-display-function-fallback)
        (counsel-describe-variable  . ivy-display-function-fallback)
        (counsel-find-file          . ivy-display-function-fallback)
        (counsel-recentf            . ivy-display-function-fallback)
        (counsel-register           . ivy-posframe-display-at-frame-bottom-window-center)
        (dmenu                      . ivy-posframe-display-at-frame-top-center)
        (nil                        . ivy-posframe-display))
      ivy-posframe-height-alist
      '((swiper . 20)
        (dmenu . 20)
        (t . 10)))
(ivy-posframe-mode 1) ; 1 enables posframe-mode, 0 disables it.
#+END_SRC

*** IVY KEYBINDINGS
By default, Doom Emacs does not use 'SPC v', so the format I use for these bindings is 'SPC v' plus 'key'.

#+BEGIN_SRC emacs-lisp
(map! :leader
      (:prefix ("v" . "Ivy")
       :desc "Ivy push view" "v p" #'ivy-push-view
       :desc "Ivy switch view" "v s" #'ivy-switch-view))
#+END_SRC


** EMOJIS
Emojify is an Emacs extension to display emojis. It can display github style emojis like :smile: or plain ascii ones like :).

#+begin_src emacs-lisp
(use-package emojify
  :hook (after-init . global-emojify-mode))
#+end_src


** START PAGE
Instead of using Doom's Dashboard or the Emacs Dashboard program, I have decided to just set an custom start file as my "dashboard" since it allows me more customization options.  I have added to the 'start-mode-hook' the argument 'read-only-mode'.  This is to prevent accidental editing of the start file, and to prevent clashes with the 'start-mode' specific keybindings.  You can toggle on/off read-only-mode with 'SPC t r'.

#+begin_src emacs-lisp
(setq initial-buffer-choice "~/.config/doom/start.org")

(define-minor-mode start-mode
  "Provide functions for custom start page."
  :lighter " start"
  :keymap (let ((map (make-sparse-keymap)))
          ;;(define-key map (kbd "M-z") 'eshell)
            (evil-define-key 'normal start-mode-map
              (kbd "1") '(lambda () (interactive) (find-file "~/.config/doom/config.org"))
              (kbd "2") '(lambda () (interactive) (find-file "~/.config/doom/init.el"))
              (kbd "3") '(lambda () (interactive) (find-file "~/.config/doom/packages.el"))
              (kbd "4") '(lambda () (interactive) (find-file "~/.config/doom/eshell/aliases"))
              (kbd "5") '(lambda () (interactive) (find-file "~/.config/doom/eshell/profile")))
          map))

(add-hook 'start-mode-hook 'read-only-mode) ;; make start.org read-only; use 'SPC t r' to toggle off read-only.
(provide 'start-mode)
#+end_src


** GNUS FACE INHERITANCE CYCLE FIX
doom-themes makes ~gnus-group-news-low-empty~ inherit ~gnus-group-news-low~,
while Emacs's built-in defface makes ~gnus-group-news-low~ inherit
~gnus-group-news-low-empty~. That mutual reference is a cycle that Emacs HEAD
(32.x) treats as a hard error, surfacing via face resolution (e.g. company-box).
Pin both faces to terminal parents to break the loop.
#+BEGIN_SRC emacs-lisp
(custom-set-faces!
  '(gnus-group-news-low       :inherit gnus-group-mail-1       :weight normal)
  '(gnus-group-news-low-empty :inherit gnus-group-mail-1-empty :weight normal))
#+END_SRC





* CODING / LSP
** ELDOC
#+begin_src emacs-lisp
(add-hook 'eldoc-mode-hook #'eldoc-box-hover-mode)
#+end_src


** EGLOT
#+begin_src emacs-lisp
(use-package! eglot
  :defer t
  :hook ((go-mode . eglot-ensure)
         (go-ts-mode . eglot-ensure)
         (python-mode . eglot-ensure)
         (python-ts-mode . eglot-ensure)
         (sh-mode . eglot-ensure)
         (bash-ts-mode . eglot-ensure) ;; bash, zsh, etc.
         (clojure-mode . eglot-ensure)
         (clojurec-mode . eglot-ensure)
         (clojurescript-mode . eglot-ensure))
  :config
  ;; Optional: Tweak formatting and UI
  (setq eglot-events-buffer-size 0)

  ;; Setup server program paths if needed
  (add-to-list 'eglot-server-programs
               `(sh-mode . ("bash-language-server" "start")))

  ;; For Go: use goimports for formatting
  (setq gofmt-command "goimports")
  ;; Ignore file watching to avoid FD exhaustion on large projects
  (setq eglot-ignored-server-capabilities '(:documentFormattingProvider
                                            :documentOnTypeFormattingProvider))

  ;; Optional: keybindings
  (map! :leader
        (:prefix ("c" . "code")
         :desc "Find definitions" "d" #'xref-find-definitions
         :desc "Find references"  "r" #'xref-find-references
         :desc "Rename symbol"    "R" #'eglot-rename
         :desc "Format buffer"    "f" #'eglot-format)))
#+end_src

** DAPE
#+begin_src emacs-lisp
(defun my/project-root-or-default ()
  "Return project root, or `default-directory` if not in a project."
  (or (when-let ((p (project-current nil)))
        (project-root p))
      default-directory))

(after! dape
  (add-to-list 'dape-configs
               `(go-test-package
                 modes (go-mode go-ts-mode)
                 command "dlv"
                 command-args ("test")
                 :type "go"
                 :request "launch"
                 :cwd ,#'my/project-root-or-default
                 :program ,#'my/project-root-or-default))

  (add-to-list 'dape-configs
               `(go-run-main
                 modes (go-mode go-ts-mode)
                 command "dlv"
                 command-args ("debug")
                 :type "go"
                 :request "launch"
                 :cwd ,#'my/project-root-or-default
                 :program ,#'my/project-root-or-default)))

(defun my/dape-go-interactive-launch ()
  "Interactively launch Delve via DAPE with custom CWD, args, and optional test filter."
  (interactive)
  (let* ((default-cwd (or (when-let ((p (project-current))) (project-root p)) default-directory))
         (cwd (read-directory-name "CWD: " default-cwd nil t))
         (mode (completing-read "Delve mode: " '("debug" "test" "exec") nil t))
         (extra-args (read-string "Extra dlv args (space-separated): " nil nil ""))
         (test-name (when (string= mode "test")
                      (read-string "Run specific test regex (empty=all): " nil nil "")))
         (args (split-string (or extra-args "") "[[:space:]]+" t))
         (command-args
          (append (list mode)
                  (when (and (string= mode "test") (not (string-empty-p test-name)))
                    (list "--" (format "-test.run=%s" test-name)))
                  args)))
    (dape (list :type "go"
                :request "launch"
                :command (executable-find "dlv")
                :command-args command-args
                :cwd (expand-file-name cwd)
                :program (expand-file-name cwd)))))

(map! :leader
      (:prefix ("d" . "debug")
       :desc "Go DAPE custom launch" "g c" #'my/dape-go-interactive-launch))

(after! dape
  (add-to-list 'dape-configs
               `(aqua-server
                 modes (go-mode go-ts-mode)
                 command "dlv"
                 command-args ("dap" "--listen" "127.0.0.1:55878")
                 command-cwd default-directory
                 host "127.0.0.1"
                 port 55878
                 :request "launch"
                 :type "debug"
                 :cwd "/Users/hadil-sabbagh/projects/aqua/webservices"
                 :program "/Users/hadil-sabbagh/projects/aqua/webservices/cmd/server")))

#+end_src

** CLOJURE
#+begin_src emacs-lisp
;; clojure-lsp is wired through EGLOT (see the EGLOT block); the +lsp flag on the
;; clojure module in init.el is what makes Doom install and register it.
(after! clojure-mode
  (dolist (hook '(clojure-mode-hook clojurec-mode-hook clojurescript-mode-hook))
    (add-hook hook #'rainbow-delimiters-mode)
    (add-hook hook #'smartparens-strict-mode)))
#+end_src

** PYTHON
#+begin_src emacs-lisp

  ;; Use apheleia + ruff for formatting and import sorting
  (after! apheleia
    (setf (alist-get 'ruff-isort apheleia-formatters)
          '("ruff" "check" "--select" "I" "--fix-only" "--stdin-filename" filepath "-"))
    (setf (alist-get 'ruff apheleia-formatters)
          '("ruff" "format" "--stdin-filename" filepath "-"))
    (setf (alist-get 'python-mode apheleia-mode-alist) '(ruff-isort ruff))
    (setf (alist-get 'python-ts-mode apheleia-mode-alist) '(ruff-isort ruff)))

;; python-mode and python-ts-mode already get eglot via the eglot :hook above.

(after! eglot
  ;; Prefer pyright if available, otherwise pylsp.
  ;; Eglot will auto-detect some servers, but being explicit avoids surprises.
  (add-to-list 'eglot-server-programs
               '((python-mode python-ts-mode)
                 . ("pyright-langserver" "--stdio")))
  ;; If you prefer pylsp, use this instead:
  ;; (add-to-list 'eglot-server-programs
  ;;              '((python-mode python-ts-mode) . ("pylsp")))
  ;;
  ;; Make Eldoc show more eagerly (hover/docs in minibuffer)
  (setq eldoc-echo-area-use-multiline-p t))

(after! eglot
  (require 'cl-lib)

  ;; Proactively skip file watcher registrations to avoid FD exhaustion.
  ;; This filters out didChangeWatchedFiles before eglot tries to set them up.
  (cl-defmethod eglot-handle-request
    (server (_method (eql client/registerCapability)) &rest params)
    (let* ((registrations (plist-get (car params) :registrations))
           (dominated-registrations
            (seq-filter
             (lambda (reg)
               (not (string= (plist-get reg :method) "workspace/didChangeWatchedFiles")))
             registrations)))
      (if (equal registrations dominated-registrations)
          (cl-call-next-method)
        (message "[eglot] Skipping file watcher registration (FD limit workaround)")
        nil))))

(after! flycheck
  ;; Disable flycheck for Go and Python modes (use eglot/flymake instead)
  (add-hook 'go-mode-hook (lambda () (flycheck-mode -1)))
  (add-hook 'go-ts-mode-hook (lambda () (flycheck-mode -1)))
  (add-hook 'python-mode-hook (lambda () (flycheck-mode -1)))
  (add-hook 'python-ts-mode-hook (lambda () (flycheck-mode -1))))

;; Ruff linting via flymake (works alongside eglot/pyright diagnostics)
(use-package! flymake-ruff
  :hook ((python-mode . flymake-ruff-load)
         (python-ts-mode . flymake-ruff-load)))

(use-package! eldoc-box
  :hook (eglot-managed-mode . eldoc-box-hover-at-point-mode)
  :config
  (setq eldoc-box-clear-with-C-g t))


(defun copy-file-path-with-line (&optional absolute)
  "Copy current file path with line number (or region range) to clipboard.
Uses project-relative path by default. With prefix arg, use absolute path."
  (interactive "P")
  (if-let ((file-path (buffer-file-name)))
      (let* ((path (if (and (not absolute) (project-current))
                       (file-relative-name file-path (project-root (project-current)))
                     file-path))
             (line-start (line-number-at-pos
                          (if (use-region-p) (region-beginning) (point))))
             (line-end (when (use-region-p)
                         (line-number-at-pos
                          (if (and (> (region-end) (region-beginning))
                                   (= (char-before (region-end)) ?\n))
                              (1- (region-end))
                            (region-end)))))
             (result (if line-end
                         (format "%s:%d-%d" path line-start line-end)
                       (format "%s:%d" path line-start))))
        (kill-new result)
        (message "Copied: %s" result))
    (message "Buffer is not visiting a file")))

;; (map! :leader
;;       (:prefix "l"
;;        :desc "Copy path:line" "y" #'copy-file-path-with-line))
#+end_src


** MARKDOWN
#+begin_src emacs-lisp
(after! markdown-mode
  (defun +markdown/open-with-mdopen ()
    "Open current markdown file in mdopen, scoped to its directory."
    (interactive)
    (unless buffer-file-name
      (user-error "Buffer is not visiting a file"))
    ;; mdopen 0.5 binds port 5032 at startup and serves only the files
    ;; passed on its command line — there is no protocol to ask a running
    ;; instance to switch files. A second `mdopen FILE` exits with
    ;; "Address already in use", and because start-process discards stderr
    ;; the failure is silent and the browser never navigates. Tear down
    ;; any running instance (Emacs-managed or external) first.
    (call-process "/usr/bin/pkill" nil nil nil "-x" "mdopen")
    (let ((default-directory (file-name-directory buffer-file-name)))
      (start-process "mdopen" nil "mdopen"
                     (file-name-nondirectory buffer-file-name)))
    (message "mdopen serving %s" buffer-file-name))

  ;; Also fix the built-in SPC m o path so both keybinds work
  (setq markdown-open-command nil)
  (advice-add 'markdown-open :override #'+markdown/open-with-mdopen)

  (map! :map markdown-mode-map
        :localleader
        "p" #'+markdown/open-with-mdopen))
#+end_src


#+begin_src emacs-lisp
(custom-set-faces
 '(markdown-header-face ((t (:inherit font-lock-function-name-face :weight bold :family "variable-pitch"))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face :height 1.7))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face :height 1.6))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face :height 1.5))))
 '(markdown-header-face-4 ((t (:inherit markdown-header-face :height 1.4))))
 '(markdown-header-face-5 ((t (:inherit markdown-header-face :height 1.3))))
 '(markdown-header-face-6 ((t (:inherit markdown-header-face :height 1.2)))))

#+end_src


** CLAUDE CODE IDE
#+begin_src emacs-lisp
(use-package! claude-code-ide
  :bind ("C-c C-'" . claude-code-ide-menu) ; Set your favorite keybinding
  :init
  ;; Doom-idiomatic SPC-l prefix, alongside C-c C-'.
  (map! :leader
        (:prefix ("l" . "claude")
         :desc "Menu"          "l" #'claude-code-ide-menu
         :desc "Start/toggle"  "c" #'claude-code-ide
         :desc "Continue"      "C" #'claude-code-ide-continue
         :desc "Resume picker" "r" #'claude-code-ide-resume
         :desc "Send prompt"   "p" #'claude-code-ide-send-prompt
         :desc "Insert region" "i" #'claude-code-ide-insert-at-mentioned
         :desc "Toggle window" "t" #'claude-code-ide-toggle
         :desc "Sessions"      "s" #'claude-code-ide-list-sessions
         :desc "Stop"          "k" #'claude-code-ide-stop))
  :config
  ;; Give the side window time to finish laying out before the TUI
  ;; measures its size, otherwise the input box can render mid-buffer.
  (setq claude-code-ide-terminal-initialization-delay 0.5
        claude-code-ide-prevent-reflow-glitch t
        claude-code-ide-vterm-anti-flicker t
        claude-code-ide-vterm-render-delay 0.03
        claude-code-ide-no-flicker t
        claude-code-ide-terminal-backend 'ghostel
        ;; Window placement
        claude-code-ide-use-side-window t
        claude-code-ide-window-side 'right
        claude-code-ide-window-width 100
        claude-code-ide-focus-on-open t
        ;; Ediff-based diffs (matches the openDiff path)
        claude-code-ide-use-ide-diff t
        claude-code-ide-focus-claude-after-ediff t
        claude-code-ide-show-claude-window-in-ediff t
        claude-code-ide-switch-tab-on-ediff t
        ;; Diagnostics — Doom uses flycheck; 'auto picks it up.
        claude-code-ide-diagnostics-backend 'auto
        ;; MCP — exposes xref / tree-sitter / imenu / project to Claude.
        claude-code-ide-enable-mcp-server t
        claude-code-ide-enable-execute-code t)
  (claude-code-ide-emacs-tools-setup) ; Optionally enable Emacs MCP tools

  ;; Let claude-code-ide manage its own side window; tell Doom's popup
  ;; manager to stay out of the way so the two don't fight over placement.
  (set-popup-rule! "^\\*claude-code" :ignore t)

  ;; Mouse wheel throttle in Claude buffers. macOS momentum scrolling emits a
  ;; flood of wheel events per flick, so Claude's transcript scrolls far too
  ;; fast. The knob below decimates them: only one of every
  ;; `my/claude-code-ide-wheel-divisor' events is acted on. Raise the divisor
  ;; to slow scrolling further; set it to 1 for the native speed.
  ;;
  ;; The hard part is *where* to intercept under the ghostel backend. Ghostel
  ;; grabs the wheel through `emulation-mode-map-alists' — the highest keymap
  ;; tier — so terminal apps (vim, htop) can see it; it then forwards the
  ;; wheel to the pty as mouse button 4/5, which is what actually scrolls
  ;; Claude. A buffer-local `local-set-key' can never outrank that, which is
  ;; why the divisor used to have no effect on ghostel. So we register our OWN
  ;; emulation entry *ahead* of ghostel's, gated on a buffer-local flag set
  ;; only in Claude buffers; for the one-in-N events we keep, we re-inject them
  ;; so ghostel's own handler forwards them normally (decimation, not
  ;; re-encoding — robust to however ghostel scrolls). Under vterm there is no
  ;; such competitor, so we synthesize Meta+j/Meta+k there instead.
  (defvar my/claude-code-ide-wheel-divisor 6
    "Wheel events per acted-on scroll step in Claude buffers. Higher = slower.")
  (defvar-local my/claude-code-ide--wheel-accum 0
    "Signed accumulator of wheel events since the last acted-on step.")
  (defvar-local my/claude-code-ide--wheel-intercept nil
    "Non-nil in Claude buffers to activate the wheel-throttle emulation map.")
  (defun my/claude-code-ide--reenable-intercept ()
    "Re-arm the throttle intercept after one re-injected wheel event."
    (setq my/claude-code-ide--wheel-intercept t)
    (remove-hook 'pre-command-hook #'my/claude-code-ide--reenable-intercept t))
  (defun my/claude-code-ide--wheel (event dir)
    "Act on one of every `my/claude-code-ide-wheel-divisor' wheel events.
EVENT is the wheel event; DIR is -1 (up) or +1 (down)."
    ;; Reset on a direction flip so reversing responds immediately.
    (unless (eq (cl-signum my/claude-code-ide--wheel-accum) dir)
      (setq my/claude-code-ide--wheel-accum 0))
    (cl-incf my/claude-code-ide--wheel-accum dir)
    (when (>= (abs my/claude-code-ide--wheel-accum)
              my/claude-code-ide-wheel-divisor)
      (setq my/claude-code-ide--wheel-accum 0)
      (cond
       ;; Ghostel: let this one event fall through to ghostel's own wheel
       ;; handler (which forwards it to the pty). Disable our higher-priority
       ;; intercept, re-inject the event, and re-arm on the next command.
       ((derived-mode-p 'ghostel-mode)
        (setq my/claude-code-ide--wheel-intercept nil)
        (setq unread-command-events (cons event unread-command-events))
        (add-hook 'pre-command-hook #'my/claude-code-ide--reenable-intercept nil t))
       ;; Vterm: synthesize a scroll keystroke instead.
       ((derived-mode-p 'vterm-mode)
        (vterm-send-key (if (> dir 0) "j" "k") nil t nil)))))
  (defun my/claude-code-ide-wheel-up (event)
    (interactive "e")
    (my/claude-code-ide--wheel event -1))
  (defun my/claude-code-ide-wheel-down (event)
    (interactive "e")
    (my/claude-code-ide--wheel event 1))
  (defvar-keymap my/claude-code-ide--wheel-map
    :doc "High-priority wheel-throttle keymap for Claude buffers."
    "<wheel-up>"          #'my/claude-code-ide-wheel-up
    "<double-wheel-up>"   #'my/claude-code-ide-wheel-up
    "<triple-wheel-up>"   #'my/claude-code-ide-wheel-up
    "<wheel-down>"        #'my/claude-code-ide-wheel-down
    "<double-wheel-down>" #'my/claude-code-ide-wheel-down
    "<triple-wheel-down>" #'my/claude-code-ide-wheel-down)
  (defvar my/claude-code-ide--wheel-emulation-alist
    `((my/claude-code-ide--wheel-intercept . ,my/claude-code-ide--wheel-map))
    "`emulation-mode-map-alists' entry; active per-buffer via the flag above.")
  (advice-add
   'claude-code-ide--setup-terminal-keybindings :after
   (defun my/claude-code-ide-bind-wheel ()
     ;; Only meaningful with no-flicker on (Claude owns the transcript; native
     ;; Emacs scroll is inert). Arm our throttle in this buffer and re-assert
     ;; our emulation entry at the front — ghostel prepends its own entry when
     ;; it loads (after our config), and this advice runs per session *after*
     ;; ghostel is up, so this is where we can reliably win the priority race.
     (when (and claude-code-ide-no-flicker
                (derived-mode-p 'vterm-mode 'ghostel-mode))
       (setq my/claude-code-ide--wheel-intercept t)
       (setq emulation-mode-map-alists
             (cons 'my/claude-code-ide--wheel-emulation-alist
                   (delq 'my/claude-code-ide--wheel-emulation-alist
                         emulation-mode-map-alists)))))))
#+end_src

* ORG
** Org directory
Set =org-directory= before Org loads (must precede the package).
#+begin_src emacs-lisp
(setq org-directory "~/Documents/org/")
#+end_src

** ORG MODE
I wrapped most of this block in (after! org).  Without this, my settings might be evaluated too early, which will result in my settings being overwritten by Doom's defaults.  I have also enabled org-journal, org-superstar and org-roam by adding (+journal +pretty +roam2) to the org section of my Doom Emacs init.el.

=NOTE=: I have the location of my Org directory and Roam directory in $HOME/nc/ which is a Nextcloud folder that allows me to instantly sync all of my Org work between my home computer and my office computer.

#+BEGIN_SRC emacs-lisp
(map! :leader
      :desc "Org babel tangle" "m B" #'org-babel-tangle)
(after! org
  (setq org-default-notes-file (expand-file-name "notes.org" org-directory)
        org-ellipsis " ▼ "
        org-superstar-headline-bullets-list '("◉" "●" "○" "◆" "●" "○" "◆")
        org-superstar-itembullet-alist '((?+ . ?➤) (?- . ?✦)) ; changes +/- symbols in item lists
        org-log-done 'time
        org-hide-emphasis-markers t
        ;; ex. of org-link-abbrev-alist in action
        ;; [[arch-wiki:Name_of_Page][Description]]
        org-link-abbrev-alist    ; This overwrites the default Doom org-link-abbrev-list
          '(("google" . "http://www.google.com/search?q=")
            ("arch-wiki" . "https://wiki.archlinux.org/index.php/")
            ("ddg" . "https://duckduckgo.com/?q=")
            ("wiki" . "https://en.wikipedia.org/wiki/"))
        org-table-convert-region-max-lines 20000
        org-todo-keywords        ; This overwrites the default Doom org-todo-keywords
          '((sequence
             "TODO(t)"           ; A task that is ready to be tackled
             "BLOG(b)"           ; Blog writing assignments
             "GYM(g)"            ; Things to accomplish at the gym
             "PROJ(p)"           ; A project that contains other tasks
             "VIDEO(v)"          ; Video assignments
             "WAIT(w)"           ; Something is holding up this task
             "|"                 ; The pipe necessary to separate "active" states and "inactive" states
             "DONE(d)"           ; Task has been completed
             "CANCELLED(c)" )))) ; Task has been cancelled
#+END_SRC

*** Org-agenda
#+begin_src emacs-lisp
(after! org
  (setq org-agenda-files '("~/Documents/org/agenda.org")))

(setq
   ;; org-fancy-priorities-list '("[A]" "[B]" "[C]")
   ;; org-fancy-priorities-list '("❗" "[B]" "[C]")
   org-fancy-priorities-list '("🟥" "🟧" "🟨")
   org-priority-faces
   '((?A :foreground "#ff6c6b" :weight bold)
     (?B :foreground "#98be65" :weight bold)
     (?C :foreground "#c678dd" :weight bold))
   org-agenda-block-separator 8411)

(setq org-agenda-custom-commands
      '(("v" "A better agenda view"
         ((tags "PRIORITY=\"A\""
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "High-priority unfinished tasks:")))
          (tags "PRIORITY=\"B\""
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "Medium-priority unfinished tasks:")))
          (tags "PRIORITY=\"C\""
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "Low-priority unfinished tasks:")))
          (tags "customtag"
                ((org-agenda-skip-function '(org-agenda-skip-entry-if 'todo 'done))
                 (org-agenda-overriding-header "Tasks marked with customtag:")))

          (agenda "")
          (alltodo "")))))
#+end_src

*** Org-auto-tangle
=org-auto-tangle= allows you to add the option =#+auto_tangle: t= in your Org file so that it automatically tangles when you save the document.  I have made adding this to your file even easier by creating a function 'dt/insert-auto-tangle-tag' and setting it to a keybinding 'SPC i a'.

#+begin_src emacs-lisp
(use-package! org-auto-tangle
  :defer t
  :hook (org-mode . org-auto-tangle-mode)
  :config
  (setq org-auto-tangle-default t))

(defun dt/insert-auto-tangle-tag ()
  "Insert auto-tangle tag in a literate config."
  (interactive)
  (evil-org-open-below 1)
  (insert "#+auto_tangle: t ")
  (evil-force-normal-state))

(map! :leader
      :desc "Insert auto_tangle tag" "i a" #'dt/insert-auto-tangle-tag)
#+end_src

*** Org fonts
I have created an interactive function for each color scheme (M-x dt/org-colors-*).  These functions will set appropriate colors and font attributes for org-level fonts and the org-table font.

#+begin_src emacs-lisp
(defun dt/org-colors-doom-one ()
  "Enable Doom One colors for Org headers."
  (interactive)
  (dolist
      (face
       '((org-level-1 1.7 "#51afef" ultra-bold)
         (org-level-2 1.6 "#c678dd" extra-bold)
         (org-level-3 1.5 "#98be65" bold)
         (org-level-4 1.4 "#da8548" semi-bold)
         (org-level-5 1.3 "#5699af" normal)
         (org-level-6 1.2 "#a9a1e1" normal)
         (org-level-7 1.1 "#46d9ff" normal)
         (org-level-8 1.0 "#ff6c6b" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

(defun dt/org-colors-dracula ()
  "Enable Dracula colors for Org headers."
  (interactive)
  (dolist
      (face
       '((org-level-1 1.7 "#8be9fd" ultra-bold)
         (org-level-2 1.6 "#bd93f9" extra-bold)
         (org-level-3 1.5 "#50fa7b" bold)
         (org-level-4 1.4 "#ff79c6" semi-bold)
         (org-level-5 1.3 "#9aedfe" normal)
         (org-level-6 1.2 "#caa9fa" normal)
         (org-level-7 1.1 "#5af78e" normal)
         (org-level-8 1.0 "#ff92d0" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

(defun dt/org-colors-gruvbox-dark ()
  "Enable Gruvbox Dark colors for Org headers."
  (interactive)
  (dolist
      (face
       '((org-level-1 1.7 "#458588" ultra-bold)
         (org-level-2 1.6 "#b16286" extra-bold)
         (org-level-3 1.5 "#98971a" bold)
         (org-level-4 1.4 "#fb4934" semi-bold)
         (org-level-5 1.3 "#83a598" normal)
         (org-level-6 1.2 "#d3869b" normal)
         (org-level-7 1.1 "#d79921" normal)
         (org-level-8 1.0 "#8ec07c" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

(defun dt/org-colors-monokai-pro ()
  "Enable Monokai Pro colors for Org headers."
  (interactive)
  (dolist
      (face
       '((org-level-1 1.7 "#78dce8" ultra-bold)
         (org-level-2 1.6 "#ab9df2" extra-bold)
         (org-level-3 1.5 "#a9dc76" bold)
         (org-level-4 1.4 "#fc9867" semi-bold)
         (org-level-5 1.3 "#ff6188" normal)
         (org-level-6 1.2 "#ffd866" normal)
         (org-level-7 1.1 "#78dce8" normal)
         (org-level-8 1.0 "#ab9df2" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

(defun dt/org-colors-nord ()
  "Enable Nord colors for Org headers."
  (interactive)
  (dolist
      (face
       '((org-level-1 1.7 "#81a1c1" ultra-bold)
         (org-level-2 1.6 "#b48ead" extra-bold)
         (org-level-3 1.5 "#a3be8c" bold)
         (org-level-4 1.4 "#ebcb8b" semi-bold)
         (org-level-5 1.3 "#bf616a" normal)
         (org-level-6 1.2 "#88c0d0" normal)
         (org-level-7 1.1 "#81a1c1" normal)
         (org-level-8 1.0 "#b48ead" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

(defun dt/org-colors-oceanic-next ()
  "Enable Oceanic Next colors for Org headers."
  (interactive)
  (dolist
      (face
       '((org-level-1 1.7 "#6699cc" ultra-bold)
         (org-level-2 1.6 "#c594c5" extra-bold)
         (org-level-3 1.5 "#99c794" bold)
         (org-level-4 1.4 "#fac863" semi-bold)
         (org-level-5 1.3 "#5fb3b3" normal)
         (org-level-6 1.2 "#ec5f67" normal)
         (org-level-7 1.1 "#6699cc" normal)
         (org-level-8 1.0 "#c594c5" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

(defun dt/org-colors-palenight ()
  "Enable Palenight colors for Org headers."
  (interactive)
  (dolist
      (face
       '((org-level-1 1.7 "#82aaff" ultra-bold)
         (org-level-2 1.6 "#c792ea" extra-bold)
         (org-level-3 1.5 "#c3e88d" bold)
         (org-level-4 1.4 "#ffcb6b" semi-bold)
         (org-level-5 1.3 "#a3f7ff" normal)
         (org-level-6 1.2 "#e1acff" normal)
         (org-level-7 1.1 "#f07178" normal)
         (org-level-8 1.0 "#ddffa7" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

(defun dt/org-colors-solarized-dark ()
  "Enable Solarized Dark colors for Org headers."
  (interactive)
  (dolist
      (face
       '((org-level-1 1.7 "#268bd2" ultra-bold)
         (org-level-2 1.6 "#d33682" extra-bold)
         (org-level-3 1.5 "#859900" bold)
         (org-level-4 1.4 "#b58900" semi-bold)
         (org-level-5 1.3 "#cb4b16" normal)
         (org-level-6 1.2 "#6c71c4" normal)
         (org-level-7 1.1 "#2aa198" normal)
         (org-level-8 1.0 "#657b83" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

(defun dt/org-colors-solarized-light ()
  "Enable Solarized Light colors for Org headers."
  (interactive)
  (dolist
      (face
       '((org-level-1 1.7 "#268bd2" ultra-bold)
         (org-level-2 1.6 "#d33682" extra-bold)
         (org-level-3 1.5 "#859900" bold)
         (org-level-4 1.4 "#b58900" semi-bold)
         (org-level-5 1.3 "#cb4b16" normal)
         (org-level-6 1.2 "#6c71c4" normal)
         (org-level-7 1.1 "#2aa198" normal)
         (org-level-8 1.0 "#657b83" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

(defun dt/org-colors-tomorrow-night ()
  "Enable Tomorrow Night colors for Org headers."
  (interactive)
  (dolist
      (face
       '((org-level-1 1.7 "#81a2be" ultra-bold)
         (org-level-2 1.6 "#b294bb" extra-bold)
         (org-level-3 1.5 "#b5bd68" bold)
         (org-level-4 1.4 "#e6c547" semi-bold)
         (org-level-5 1.3 "#cc6666" normal)
         (org-level-6 1.2 "#70c0ba" normal)
         (org-level-7 1.1 "#b77ee0" normal)
         (org-level-8 1.0 "#9ec400" normal)))
    (set-face-attribute (nth 0 face) nil :font doom-variable-pitch-font :weight (nth 3 face) :height (nth 1 face) :foreground (nth 2 face)))
    (set-face-attribute 'org-table nil :font doom-font :weight 'normal :height 1.0 :foreground "#bfafdf"))

;; Load our desired dt/org-colors-* theme on startup.
;; Deferred until org loads so the `org-level-*'/`org-table' faces exist;
;; calling it at config-load time errors ("Invalid face: org-level-1") on
;; Emacs HEAD, where set-face-attribute rejects not-yet-defined faces.
(after! org
  (dt/org-colors-doom-one))
#+end_src

*** Org-export
We need ox-man for "Org eXporting" to manpage format and ox-gemini for exporting to gemtext (for the gemini protocol).

=NOTE=: I also enable ox-publish for converting an Org site into an HTML site, but that is done in init.el (org +publish).

#+BEGIN_SRC emacs-lisp
(use-package ox-man)
(use-package ox-gemini)
#+END_SRC

*** Org-journal
#+begin_src emacs-lisp
(setq org-journal-dir "~/Documents/org/journal/"
      org-journal-date-prefix "* "
      org-journal-time-prefix "** "
      org-journal-date-format "%B %d, %Y (%A) "
      org-journal-file-format "%Y-%m-%d.org")
#+end_src

*** Org-publish
#+begin_src emacs-lisp
(setq org-publish-use-timestamps-flag nil)
(setq org-export-with-broken-links t)
(setq org-publish-project-alist
      '(("distro.tube without manpages"
         :base-directory "~/nc/gitlab-repos/distro.tube/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/"
         :recursive t
         :exclude "org-html-themes/.*\\|man-org/man*"
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("man0p"
         :base-directory "~/nc/gitlab-repos/distro.tube/man-org/man0p/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/man-org/man0p/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("man1"
         :base-directory "~/nc/gitlab-repos/distro.tube/man-org/man1/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/man-org/man1/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("man1p"
         :base-directory "~/nc/gitlab-repos/distro.tube/man-org/man1p/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/man-org/man1p/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("man2"
         :base-directory "~/nc/gitlab-repos/distro.tube/man-org/man2/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/man-org/man2/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("man3"
         :base-directory "~/nc/gitlab-repos/distro.tube/man-org/man3/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/man-org/man3/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("man3p"
         :base-directory "~/nc/gitlab-repos/distro.tube/man-org/man3p/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/man-org/man3p/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("man4"
         :base-directory "~/nc/gitlab-repos/distro.tube/man-org/man4/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/man-org/man4/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("man5"
         :base-directory "~/nc/gitlab-repos/distro.tube/man-org/man5/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/man-org/man5/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("man6"
         :base-directory "~/nc/gitlab-repos/distro.tube/man-org/man6/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/man-org/man6/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("man7"
         :base-directory "~/nc/gitlab-repos/distro.tube/man-org/man7/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/man-org/man7/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("man8"
         :base-directory "~/nc/gitlab-repos/distro.tube/man-org/man8/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/distro.tube/html/man-org/man8/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)
         ("org-static"
         :base-directory "~/Org/website"
         :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf"
         :publishing-directory "~/public_html/"
         :recursive t
         :exclude ".*/org-html-themes/.*"
         :publishing-function org-publish-attachment)
         ("dtos.dev"
         :base-directory "~/nc/gitlab-repos/dtos.dev/"
         :base-extension "org"
         :publishing-directory "~/nc/gitlab-repos/dtos.dev/html/"
         :recursive t
         :publishing-function org-html-publish-to-html
         :headline-levels 4             ; Just the default for this project.
         :auto-preamble t)

      ))
#+end_src

*** Org-roam
[[https://github.com/org-roam/org-roam][Org-roam]] is a plain-text knowledge management system.  Org-roam borrows principles from the =Zettelkasten= method, providing a solution for non-hierarchical note-taking.  It should also work as a plug-and-play solution for anyone already using Org-mode for their personal wiki.

| COMMAND                | DESCRIPTION                        | KEYBINDING |
|------------------------+------------------------------------+------------|
| completion-at-point    | /Completion of node-insert at point/ | SPC n r c  |
| org-roam-node-find     | /Find node or create a new one/      | SPC n r f  |
| org-roam-graph         | /Show graph of all nodes/            | SPC n r g  |
| org-roam-node-insert   | /Insert link to a node/              | SPC n r i  |
| org-roam-capture       | /Capture to node/                    | SPC n r n  |
| org-roam-buffer-toggle | /Toggle roam buffer/                 | SPC n r r  |

#+begin_src emacs-lisp
(after! org
  (setq org-roam-directory "~/Documents/org/roam/"
        org-roam-graph-viewer "/usr/bin/brave"))

(map! :leader
      (:prefix ("n r" . "org-roam")
       :desc "Completion at point" "c" #'completion-at-point
       :desc "Find node"           "f" #'org-roam-node-find
       :desc "Show graph"          "g" #'org-roam-graph
       :desc "Insert node"         "i" #'org-roam-node-insert
       :desc "Capture to node"     "n" #'org-roam-capture
       :desc "Toggle roam buffer"  "r" #'org-roam-buffer-toggle))
#+end_src


** CALENDAR
Let's make a 12-month calendar available so we can have a calendar app that, when we click on time/date in xmobar, we get a nice 12-month calendar to view.

This is a modification of: http://homepage3.nifty.com/oatu/emacs/calendar.html
See also: https://stackoverflow.com/questions/9547912/emacs-calendar-show-more-than-3-months

#+begin_src emacs-lisp
;; https://stackoverflow.com/questions/9547912/emacs-calendar-show-more-than-3-months
(defun dt/year-calendar (&optional year)
  (interactive)
  (require 'calendar)
  (let* (
      (current-year (number-to-string (nth 5 (decode-time (current-time)))))
      (month 0)
      (year (if year year (string-to-number (format-time-string "%Y" (current-time))))))
    (switch-to-buffer (get-buffer-create calendar-buffer))
    (when (not (eq major-mode 'calendar-mode))
      (calendar-mode))
    (setq displayed-month month)
    (setq displayed-year year)
    (setq buffer-read-only nil)
    (erase-buffer)
    ;; horizontal rows
    (dotimes (j 4)
      ;; vertical columns
      (dotimes (i 3)
        (calendar-generate-month
          (setq month (+ month 1))
          year
          ;; indentation / spacing between months
          (+ 5 (* 25 i))))
      (goto-char (point-max))
      (insert (make-string (- 10 (count-lines (point-min) (point-max))) ?\n))
      (widen)
      (goto-char (point-max))
      (narrow-to-region (point-max) (point-max)))
    (widen)
    (goto-char (point-min))
    (setq buffer-read-only t)))

(defun dt/scroll-year-calendar-forward (&optional arg event)
  "Scroll the yearly calendar by year in a forward direction."
  (interactive (list (prefix-numeric-value current-prefix-arg)
                     last-nonmenu-event))
  (unless arg (setq arg 0))
  (save-selected-window
    (if (setq event (event-start event)) (select-window (posn-window event)))
    (unless (zerop arg)
      (let* (
              (year (+ displayed-year arg)))
        (dt/year-calendar year)))
    (goto-char (point-min))
    (run-hooks 'calendar-move-hook)))

(defun dt/scroll-year-calendar-backward (&optional arg event)
  "Scroll the yearly calendar by year in a backward direction."
  (interactive (list (prefix-numeric-value current-prefix-arg)
                     last-nonmenu-event))
  (dt/scroll-year-calendar-forward (- (or arg 1)) event))

(map! :leader
      :desc "Scroll year calendar backward" "<left>" #'dt/scroll-year-calendar-backward
      :desc "Scroll year calendar forward" "<right>" #'dt/scroll-year-calendar-forward)

(defalias 'year-calendar 'dt/year-calendar)
#+end_src

Let's also play around with calfw.
#+begin_src emacs-lisp
(use-package! calfw)
(use-package! calfw-org)
#+end_src


* APPS & TOOLS
** DIRED
Dired is the file manager within Emacs.  Below, I setup keybindings for image previews (peep-dired).  Doom Emacs does not use 'SPC d' for any of its keybindings, so I've chosen the format of 'SPC d' plus 'key'.

*** Keybindings To Open Dired

| COMMAND    | DESCRIPTION                        | KEYBINDING |
|------------+------------------------------------+------------|
| dired      | /Open dired file manager/            | SPC d d    |
| dired-jump | /Jump to current directory in dired/ | SPC d j    |

*** Keybindings Within Dired
**** Basic dired commands

| COMMAND                | DESCRIPTION                                 | KEYBINDING |
|------------------------+---------------------------------------------+------------|
| dired-view-file        | /View file in dired/                          | SPC d v    |
| dired-up-directory     | /Go up in directory tree/                     | h          |
| dired-find-file        | /Go down in directory tree (or open if file)/ | l          |
| dired-next-line        | /Move down to next line/                      | j          |
| dired-previous-line    | /Move up to previous line/                    | k          |
| dired-mark             | /Mark file at point/                          | m          |
| dired-unmark           | /Unmark file at point/                        | u          |
| dired-do-copy          | /Copy current file or marked files/           | C          |
| dired-do-rename        | /Rename current file or marked files/         | R          |
| dired-hide-details     | /Toggle detailed listings on/off/             | (          |
| dired-git-info-mode    | /Toggle git information on/off/               | )          |
| dired-create-directory | /Create new empty directory/                  | +          |
| dired-diff             | /Compare file at point with another/          | =          |
| dired-subtree-toggle   | /Toggle viewing subtree at point/             | TAB        |

**** Dired commands using regex

| COMMAND                 | DESCRIPTION                | KEYBINDING |
|-------------------------+----------------------------+------------|
| dired-mark-files-regexp | /Mark files using regex/     | % m        |
| dired-do-copy-regexp    | /Copy files using regex/     | % C        |
| dired-do-rename-regexp  | /Rename files using regex/   | % R        |
| dired-mark-files-regexp | /Mark all files using regex/ | * %        |

**** File permissions and ownership

| COMMAND         | DESCRIPTION                      | KEYBINDING |
|-----------------+----------------------------------+------------|
| dired-do-chgrp  | /Change the group of marked files/ | g G        |
| dired-do-chmod  | /Change the mode of marked files/  | M          |
| dired-do-chown  | /Change the owner of marked files/ | O          |
| dired-do-rename | /Rename file or all marked files/  | R          |

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("d" . "dired")
       :desc "Open dired" "d" #'dired
       :desc "Dired jump to current" "j" #'dired-jump)
      (:after dired
       (:map dired-mode-map
        :desc "Peep-dired image previews" "d p" #'peep-dired
        :desc "Dired view file"           "d v" #'dired-view-file)))

(evil-define-key 'normal dired-mode-map
  (kbd "M-RET") 'dired-display-file
  (kbd "h") 'dired-up-directory
  (kbd "l") 'dired-open-file ; use dired-find-file instead of dired-open.
  (kbd "m") 'dired-mark
  (kbd "t") 'dired-toggle-marks
  (kbd "u") 'dired-unmark
  (kbd "C") 'dired-do-copy
  (kbd "D") 'dired-do-delete
  (kbd "J") 'dired-goto-file
  (kbd "M") 'dired-do-chmod
  (kbd "O") 'dired-do-chown
  (kbd "P") 'dired-do-print
  (kbd "R") 'dired-do-rename
  (kbd "T") 'dired-do-touch
  (kbd "Y") 'dired-copy-filename-as-kill ; copies filename to kill ring.
  (kbd "Z") 'dired-do-compress
  (kbd "+") 'dired-create-directory
  (kbd "-") 'dired-do-kill-lines
  (kbd "% l") 'dired-downcase
  (kbd "% m") 'dired-mark-files-regexp
  (kbd "% u") 'dired-upcase
  (kbd "* %") 'dired-mark-files-regexp
  (kbd "* .") 'dired-mark-extension
  (kbd "* /") 'dired-mark-directories
  (kbd "; d") 'epa-dired-do-decrypt
  (kbd "; e") 'epa-dired-do-encrypt)
;; File icons + the subtree/tree column come from Doom's `(dired +icons)' flag,
;; which renders them through dirvish's `nerd-icons'/`subtree-state' attributes.
;; The old `all-the-icons-dired-mode' hook here is obsolete: that function is now
;; void (Doom dropped the package), so the hook errored on every dired open and
;; aborted dirvish's display setup — breaking the icon/tree column entirely.
;; With dired-open plugin, you can launch external programs for certain extensions
;; For example, I set all .png files to open in 'sxiv' and all .mp4 files to open in 'mpv'
(setq dired-open-extensions '(("gif" . "sxiv")
                              ("jpg" . "sxiv")
                              ("png" . "sxiv")
                              ("mkv" . "mpv")
                              ("mp4" . "mpv")))
#+end_src

*** Keybindings Within Dired With Peep-Dired-Mode Enabled
If peep-dired is enabled, you will get image previews as you go up/down with 'j' and 'k'

| COMMAND              | DESCRIPTION                              | KEYBINDING |
|----------------------+------------------------------------------+------------|
| peep-dired           | /Toggle previews within dired/             | SPC d p    |
| peep-dired-next-file | /Move to next file in peep-dired-mode/     | j          |
| peep-dired-prev-file | /Move to previous file in peep-dired-mode/ | k          |

#+BEGIN_SRC emacs-lisp
(evil-define-key 'normal peep-dired-mode-map
  (kbd "j") 'peep-dired-next-file
  (kbd "k") 'peep-dired-prev-file)
(add-hook 'peep-dired-hook 'evil-normalize-keymaps)
#+END_SRC

*** Making deleted files go to trash can
#+begin_src emacs-lisp
(setq trash-directory "~/.local/share/Trash/files/")
#+end_src

=NOTE=: For convenience, you may want to create a symlink to 'local/share/Trash' in your home directory:
#+begin_example
cd ~/
ln -s ~/.local/share/Trash .
#+end_example


** ELFEED
An RSS newsfeed reader for Emacs.

#+BEGIN_SRC emacs-lisp
;; Compatibility shim: elfeed-goodies (unmaintained) still calls
;; `elfeed-search--intro-header', which elfeed 4.0.1 removed. Without this the
;; empty-DB header path signals `void-function' on every redisplay (spamming
;; *Messages* until the first feed fetch). Delegate to elfeed's current header.
(unless (fboundp 'elfeed-search--intro-header)
  (defun elfeed-search--intro-header ()
    "Shim for `elfeed-goodies' on elfeed >= 4.0; see `elfeed-search--header'."
    (elfeed-search--header)))

(setq elfeed-goodies/entry-pane-size 0.5)

(evil-define-key 'normal elfeed-show-mode-map
  (kbd "J") 'elfeed-goodies/split-show-next
  (kbd "K") 'elfeed-goodies/split-show-prev)
(evil-define-key 'normal elfeed-search-mode-map
  (kbd "J") 'elfeed-goodies/split-show-next
  (kbd "K") 'elfeed-goodies/split-show-prev)
;; Feeds live in `org-directory'/elfeed.org: the `(rss +org)' flag pulls in
;; elfeed-org, which reads them from that outline and populates `elfeed-feeds'
;; on refresh. Managing them there (instead of a manual `elfeed-feeds' setq)
;; keeps a single source of truth.
#+END_SRC


** EMMS
One of the media players available for Emacs is emms, which stands for Emacs Multimedia System.  By default, Doom Emacs does not use 'SPC a',' so the format I use for these bindings is 'SPC a' plus 'key'.

| COMMAND               | DESCRIPTION                       | KEYBINDING |
|-----------------------+-----------------------------------+------------|
| emms-playlist-mode-go | /Switch to the playlist buffer/     | SPC a a    |
| emms-pause            | /Pause the track/                   | SPC a x    |
| emms-stop             | /Stop the track/                    | SPC a s    |
| emms-previous         | /Play previous track in playlist/   | SPC a p    |
| emms-next             | /Play next track in playlist/       | SPC a n    |

#+BEGIN_SRC emacs-lisp
(emms-all)
(emms-default-players)
(emms-mode-line 1)
(emms-playing-time 1)
(setq emms-source-file-default-directory "~/Music/"
      emms-playlist-buffer-name "*Music*"
      emms-info-asynchronously t
      emms-source-file-directory-tree-function 'emms-source-file-directory-tree-find)
(map! :leader
      (:prefix ("a" . "EMMS audio player")
       :desc "Go to emms playlist"      "a" #'emms-playlist-mode-go
       :desc "Emms pause track"         "x" #'emms-pause
       :desc "Emms stop track"          "s" #'emms-stop
       :desc "Emms play previous track" "p" #'emms-previous
       :desc "Emms play next track"     "n" #'emms-next))
#+END_SRC


** ERC
ERC is a built-in Emacs IRC client.

| COMMAND | DESCRIPTION                                 | KEYBINDING |
|---------+---------------------------------------------+------------|
| erc-tls | /Launch ERC using more secure TLS connection/ | SPC e E    |

#+begin_src emacs-lisp
(map! :leader
      (:prefix ("e". "evaluate/ERC/EWW")
       :desc "Launch ERC with TLS connection" "E" #'erc-tls))

(setq erc-prompt (lambda () (concat "[" (buffer-name) "]"))
      erc-server "irc.libera.chat"
      erc-nick "distrotube"
      erc-user-full-name "Derek Taylor"
      erc-track-shorten-start 24
      erc-autojoin-channels-alist '(("irc.libera.chat" "#archlinux" "#linux" "#emacs"))
      erc-kill-buffer-on-part t
      erc-fill-column 100
      erc-fill-function 'erc-fill-static
      erc-fill-static-center 20
      ;; erc-auto-query 'bury
      )
#+end_src


** MU4E
mu4e is a Gmail-backed mail client.  It only *reads* a local Maildir; the ~mbsync~ (isync) command in ~mu4e-get-mail-command~ pulls IMAP into ~~/.mail/gmail~, and ~msmtp~ sends.  Credentials for both live in the macOS Keychain (see ~~/.mbsyncrc~ and ~~/.msmtprc~), so no App Password is stored in plain text.  The ~+gmail~ module flag makes archive/trash defer to Gmail's own semantics.  Open the mail dashboard with 'SPC o m'.

| COMMAND | DESCRIPTION       | KEYBINDING |
|---------+-------------------+------------|
| =mu4e=    | /Open mail/         | SPC o m    |
| mu4e-compose-new | /Compose mail/ | SPC o M    |

#+begin_src emacs-lisp
;; Homebrew's `mu' installs mu4e into a *nested* site-lisp subdir
;; (<prefix>/share/emacs/site-lisp/mu/mu4e).  Emacs.app only auto-adds the
;; top-level site-lisp to `load-path', so mu4e is one level too deep to be
;; found, and Doom's mu4e module (which doesn't bundle mu4e — it ships with the
;; `mu' binary) fails to load: "Cannot open load file: mu4e".  Derive the dir
;; from the `mu' binary so it survives prefix/version changes.
(when-let* ((mu (executable-find "mu"))
            (dir (expand-file-name "../share/emacs/site-lisp/mu/mu4e"
                                   (file-name-directory mu)))
            ((file-directory-p dir)))
  (add-load-path! dir))

;; Put Homebrew's info dir on `Info-directory-list' so `C-h i' / `M-x info'
;; can find the mu4e manual (mu4e.info.gz) — Emacs.app doesn't inherit the
;; shell INFOPATH, so bundled-tool manuals are otherwise invisible.
(after! info
  (when (file-directory-p "/opt/homebrew/share/info")
    (add-to-list 'Info-directory-list "/opt/homebrew/share/info")))

(after! mu4e
  (setq mu4e-maildir "~/.mail/gmail"
        mu4e-get-mail-command "mbsync gmail"
        mu4e-update-interval 300              ; auto-fetch every 5 minutes
        mu4e-index-cleanup t
        mu4e-index-lazy-check t
        mu4e-change-filenames-when-moving t   ; required for mbsync
        mu4e-context-policy 'pick-first
        ;; Identity
        user-mail-address "hadilsabbagh18@gmail.com"
        user-full-name "Hadil Sabbagh"
        ;; Gmail's special folders (the +gmail flag handles the rest)
        mu4e-sent-folder   "/[Gmail]/Sent Mail"
        mu4e-drafts-folder "/[Gmail]/Drafts"
        mu4e-trash-folder  "/[Gmail]/Trash"
        mu4e-refile-folder "/[Gmail]/All Mail"
        ;; Send via the installed msmtp binary (reads Keychain, see ~/.msmtprc)
        sendmail-program (executable-find "msmtp")
        send-mail-function #'smtpmail-send-it
        message-sendmail-f-is-evil t
        message-sendmail-extra-arguments '("--read-envelope-from")
        message-send-mail-function #'message-send-mail-with-sendmail))

;; We dropped the evil `+everywhere' flag (no evil-collection), so mu4e's
;; navigation buffers would otherwise open in evil *normal* state, where
;; s/c/d/x/r shadow mu4e's native single-key commands.  Force the reader
;; modes into emacs state so the built-in bindings work unshadowed.  Compose
;; is left in the default (normal) state so evil editing still applies there.
(after! mu4e
  (dolist (mode '(mu4e-main-mode mu4e-headers-mode mu4e-view-mode))
    (evil-set-initial-state mode 'emacs)))

(map! :leader
      :desc "Open mu4e (mail)" "o m" #'mu4e
      :desc "Compose mail"     "o M" #'mu4e-compose-new)
#+end_src

*** New-mail desktop notifications
=mu4e-alert= is unmaintained and breaks against mu 1.14, so we notify with a
small hook on top of =alert= (see the ~alert~ block, which routes to
~terminal-notifier~ on macOS).  It fires on ~mu4e-index-updated-hook~ (after each
background fetch) whenever the unread INBOX count *rises*.

For notifications to arrive without the mu4e UI open, mu4e must be fetching in
the background — ~(mu4e t)~ starts it hidden.  We defer that to
~doom-after-init-hook~ so a mail process isn't spawned before Emacs is ready.

#+begin_src emacs-lisp
(after! mu4e
  (defvar my/mu4e-last-unread nil
    "Unread INBOX count at the previous index; nil until first measured.")

  (defun my/mu4e-unread-count ()
    "Return the number of unread messages in the INBOX via the mu index."
    (string-to-number
     (shell-command-to-string
      "mu find maildir:/Inbox flag:unread --fields i 2>/dev/null | wc -l")))

  (defun my/mu4e-notify-new-mail ()
    "Post a desktop notification when the unread INBOX count rises."
    (let ((n (my/mu4e-unread-count)))
      (when (and my/mu4e-last-unread (> n my/mu4e-last-unread))
        (let ((new (- n my/mu4e-last-unread)))
          (alert (format "%d new message%s" new (if (= new 1) "" "s"))
                 :title "mu4e")))
      (setq my/mu4e-last-unread n)))

  (add-hook 'mu4e-index-updated-hook #'my/mu4e-notify-new-mail))

;; Start mu4e hidden after startup so mail is fetched (every
;; `mu4e-update-interval' seconds) and notifications fire without the UI open.
(add-hook 'doom-after-init-hook (lambda () (mu4e t)))
#+end_src

** EWW
EWW is the Emacs Web Wowser, the builtin browser in Emacs.  Below I set urls to open in a specific browser (eww) with browse-url-browser-function.  By default, Doom Emacs does not use 'SPC e' for anything, so I choose to use the format 'SPC e' plus 'key' for these (I also use 'SPC e' for 'eval' keybindings).  I chose to use 'SPC s w' for eww-search-words because Doom Emacs uses 'SPC s' for 'search' commands.

#+BEGIN_SRC emacs-lisp
(setq browse-url-browser-function 'eww-browse-url)
(map! :leader
      :desc "Search web for text between BEG/END"
      "s w" #'eww-search-words
      (:prefix ("e" . "evaluate/ERC/EWW")
       :desc "Eww web browser" "w" #'eww
       :desc "Eww reload page" "R" #'eww-reload))
#+END_SRC


** EXWM
#+begin_src emacs-lisp
(autoload 'exwm-enable "exwm-config.el")
#+end_src


** EDNC (Notifications)
The Emacs Desktop Notification Center (EDNC) is an Emacs package written in pure Lisp that implements a desktop notifications service according to the freedesktop.org specification. EDNC aspires to be a small, but flexible drop-in replacement of standalone daemons like dunst.

=NOTE=: Ensure that no other notification daemon (such as dunst) is active to use EDNC.

=NOTE=: EDNC implements the freedesktop.org D-Bus notifications service, so it
only works on Linux. macOS has no D-Bus session bus (~dbus-registered-objects-table~
is void), so the whole block is gated to Linux.

#+begin_src emacs-lisp
(when (eq system-type 'gnu/linux)
  (ednc-mode 1)

  (defun show-notification-in-buffer (old new)
    (let ((name (format "Notification %d" (ednc-notification-id (or old new)))))
      (with-current-buffer (get-buffer-create name)
        (if new (let ((inhibit-read-only t))
                  (if old (erase-buffer) (ednc-view-mode))
                  (insert (ednc-format-notification new t))
                  (pop-to-buffer (current-buffer)))
          (kill-buffer)))))

  (add-hook 'ednc-notification-presentation-functions
            #'show-notification-in-buffer)

  (evil-define-key 'normal ednc-view-mode-map
    (kbd "d")   'ednc-dismiss-notification
    (kbd "RET") 'ednc-invoke-action
    (kbd "e")   'ednc-toggle-expanded-view))
#+end_src

*** Sending desktop notifications (all platforms)
~alert~ is the standard way for Emacs (and packages like org, ERC, mu4e) to post
desktop notifications. On macOS it routes to Notification Center via
~terminal-notifier~; on Linux it uses libnotify. Call it with
~(alert "message" :title "Title")~.

#+begin_src emacs-lisp
(use-package! alert
  :config
  (setq alert-default-style
        (cond ((eq system-type 'darwin)     'notifier)   ; terminal-notifier
              ((eq system-type 'gnu/linux)  'libnotify)
              (t 'message)))

  (defun my/notify (message &optional title)
    "Post a desktop notification via `alert'."
    (interactive "sMessage: ")
    (alert message :title (or title "Emacs"))))
#+end_src


** GHOSTEL
#+begin_src emacs-lisp
(use-package! ghostel
  :defer t
  :init
  (map! :leader
        (:prefix ("o" . "open")
         :desc "Ghostel"             "g" #'ghostel
         :desc "New ghostel session" "G" (cmd! (ghostel t)))))

#+END_SRC


** SHELLS
Settings for the various shells and terminal emulators within Emacs.

| COMMAND             | DESCRIPTION                | KEYBINDING |
|---------------------+----------------------------+------------|
| eshell              | /Launch the eshell/          | SPC e s    |
| +eshell/toggle      | /Toggle eshell popup window/ | SPC e t    |
| counsel-esh-history | /Browse the eshell history/  | SPC e h    |
| +vterm/toggle       | /Toggle vterm popup window/  | SPC v t    |

#+BEGIN_SRC emacs-lisp
(setq shell-file-name (or (executable-find "zsh") "/bin/zsh")
      vterm-max-scrollback 5000)
(setq eshell-rc-script "~/.config/doom/eshell/profile"
      eshell-aliases-file "~/.config/doom/eshell/aliases"
      eshell-history-size 5000
      eshell-buffer-maximum-lines 5000
      eshell-hist-ignoredups t
      eshell-scroll-to-bottom-on-input t
      eshell-destroy-buffer-when-process-dies t
      eshell-visual-commands'("bash" "fish" "htop" "ssh" "top" "zsh"))
(map! :leader
      :desc "Eshell"                 "e s" #'eshell
      :desc "Eshell popup toggle"    "e t" #'+eshell/toggle
      :desc "Counsel eshell history" "e h" #'counsel-esh-history
      :desc "Vterm popup toggle"     "v t" #'+vterm/toggle)
#+END_SRC


** PASSWORD STORE
Uses the standard Unix password store "pass".

#+begin_src emacs-lisp
(use-package! password-store)
#+end_src


** PERSPECTIVE
Perspective provides multiple named workspaces (or "perspectives") in Emacs, similar to having multiple desktops in window managers like Awesome and XMonad.  Each perspective has its own buffer list and its own window layout, making it easy to work on many separate projects without getting lost in all the buffers.  Switching to a perspective activates its window configuration, and when in a perspective, only its buffers are available (by default).  Doom Emacs uses 'SPC some_key' for binding some of the perspective commands, so I used this binging format for the perspective bindings that I created..

| COMMAND                    | DESCRIPTION                         | KEYBINDING |
|----------------------------+-------------------------------------+------------|
| persp-switch               | /Switch to perspective NAME/          | SPC DEL    |
| persp-switch-to-buffer     | /Switch to buffer in perspective/     | SPC ,      |
| persp-next                 | /Switch to next perspective/          | SPC ]      |
| persp-prev                 | /Switch to previous perspective/      | SPC [      |
| persp-add-buffer           | /Add a buffer to current perspective/ | SPC +      |
| persp-remove-by-name       | /Remove perspective by name/          | SPC -      |
| +workspace/switch-to-{0-9} | /Switch to workspace n/               | SPC 0-9    |

#+begin_src emacs-lisp
(map! :leader
      :desc "Switch to perspective NAME"       "DEL" #'persp-switch
      :desc "Switch to buffer in perspective"  "," #'persp-switch-to-buffer
      :desc "Switch to next perspective"       "]" #'persp-next
      :desc "Switch to previous perspective"   "[" #'persp-prev
      :desc "Add a buffer current perspective" "+" #'persp-add-buffer
      :desc "Remove perspective by name"       "-" #'persp-remove-by-name)
#+end_src


** GPTEL
[[https://github.com/karthink/gptel][gptel]] is a simple, no-frills LLM client for Emacs.  A =gptel= buffer is a
regular chat buffer; =gptel-send= (or =SPC L s=) submits the buffer/region and
streams the reply inline.  =gptel-menu= (=SPC L m=) is a transient that exposes
every option — backend, model, system prompt, scope — at point.

We register Anthropic Claude as the default backend.  The API key is read from
the =ANTHROPIC_API_KEY= environment variable at *request time* via a lambda, so
the secret never lives in this file or in =config.el=.  Note that GUI Emacs on
macOS doesn't inherit the shell environment, so that variable must be present in
Doom's env snapshot (=doom sync --env= after exporting it in your shell) for
=getenv= to see it — the same mechanism the =MACOS EXEC PATH= setup relies on.

#+begin_src emacs-lisp
(use-package! gptel
  :commands (gptel gptel-send gptel-menu)
  :init
  (map! :leader
        (:prefix ("L" . "llm/gptel")
         :desc "Open chat buffer" "L" #'gptel
         :desc "Send / stream"    "s" #'gptel-send
         :desc "Transient menu"   "m" #'gptel-menu
         :desc "Add context"      "a" #'gptel-add
         :desc "Rewrite region"   "r" #'gptel-rewrite))
  :config
  ;; Anthropic backend; key pulled from the env at request time.
  (gptel-make-anthropic "Claude"
    :stream t
    :key (lambda () (getenv "ANTHROPIC_API_KEY")))
  (setq gptel-default-mode 'org-mode
        gptel-model 'claude-sonnet-4-5
        gptel-backend (gptel-get-backend "Claude")))
#+end_src
